In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from IPython import display

In [17]:
import pandas as pd

df_train = pd.read_csv('../rithwik/cleaned_dataset_train.csv')
df_test = pd.read_csv('../rithwik/cleaned_dataset_test.csv')
df = pd.read_csv('../cleaned_dataset.csv')
list(df_train)

['Unnamed: 0', 'insult', 'comment']

In [27]:
text = df['comment'].tolist()
y = df['insult'].tolist()
vectorizer = TfidfVectorizer()

# tokenize and build vocab
vectorizer.fit(text)

test_text = df_test['comment'].tolist()
test_y = df_test['insult'].tolist()

#print(vectorizer.vocabulary_)
#print(vectorizer.idf_)

vector = vectorizer.transform(text)

print(vector.shape)
print(vector.toarray())

(3947, 15277)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(vector, y, train_size = 0.8, test_size = 0.2)

from sklearn import svm
clf = svm.SVC()
clf.fit(X_train,y_train) 


/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
predictions = clf.predict(X_test)

In [24]:
t = 0
for i in range(len(predictions)):
    if predictions[i] == y_test[i]:
        t += 1
print(t/len(predictions))
        

0.6987341772151898
