In [110]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd
import scipy.sparse as sparse
from IPython.display import display, Markdown, Latex
import numpy as np

In [111]:
df_train = pd.read_csv('../Preprocessed Data/cleaned_dataset_train.csv')
df_test = pd.read_csv('../Preprocessed Data/cleaned_dataset_test.csv')
#df = pd.read_csv('../cleaned_dataset.csv')
#df_train["comment"].fillna(" ").tolist()

In [112]:
X_train = df_train['comment'].fillna(" ").tolist()
Y_train = df_train['insult'].tolist()

X_test = df_test['comment'].fillna(" ").tolist()
Y_test = df_test['insult'].tolist()

vectorizer = TfidfVectorizer()
vectorizer.fit(X_train)

X_train = vectorizer.transform(X_train)
X_test = vectorizer.transform(X_test)
global_count = 0

In [124]:
def hasYourMom(sentence):
    return sentence.lower().count("your mom")

def wordCount(sentence):
    return len(sentence.split())

def countUpper(sentence):
    return float(sum(1 for k in sentence if k.isupper()))/len(sentence)

def countExclaim(sentence):
    return float(sentence.count('!')/float(len(sentence)))

def countAtTheRate(sentence):
    return float(sentence.count('@')/float(len(sentence)))

def countPercent(sentence):
    return float(sentence.count('%')/float(len(sentence)))

def countLeftBracket(sentence):
    return float(sentence.count('(')/float(len(sentence)))

def countQuotes(sentence):
    return float(sentence.count('"')/float(len(sentence)))

def countStar(sentence):
    return float(sentence.count('*')/float(len(sentence)))

def countBackSlashes(sentence):
    return float(sentence.count('\\')/float(len(sentence)))

def countFrontSlash(sentence):
    return float(sentence.count('/')/float(len(sentence)))

def percentCapital(sentence):
    upper = 0
    total_count = 0
    for word in sentence:
        total_count += 1
        if word.isupper():
            upper += 1
    return upper/total_count


def percentSpecial(sentence):
    global_count = 0
    global_count += countExclaim(sentence)
    #global_count += countFrontSlash(sentence)
    #global_count += countBackSlashes(sentence)
    #global_count += countQuotes(sentence)
    global_count += countPercent(sentence)
    global_count += countAtTheRate(sentence)

    return global_count/len(sentence)
            

def countYour(sentence):
    s = 0
    lst = ['your','Your','YOUR']
    for word in lst:
        s += sentence.count(word)
    return float(s)/len(sentence)

def countYou(sentence):
    s = 0
    lst = ['you','You','YOU']
    for word in lst:
        s += sentence.count(word)
    return float(s)/len(sentence)

def countBadWords(sentence):
    tmp = sentence.lower()
    badWordCount = 0
    badWordFile = open("../compiled_badword_list.txt","r")
    badWordList = badWordFile.readlines()
    for badWord in badWordList:
        bw = badWord.lower()
        if bw[:-1] in tmp:
            badWordCount += 1
    #print(len(sentence.split()))
    try:
        return badWordCount/len(sentence.split())
    except:
        return badWordCount

In [125]:
X_train = df_train['comment'].fillna(" ").tolist()
Y_train = df_train['insult'].tolist()
X_test = df_test['comment'].fillna(" ").tolist()
vectorizer = TfidfVectorizer()
vectorizer.fit(X_train)

X_train_tfidf = vectorizer.transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

X_train_tfidf = X_train_tfidf.todense()
X_test_tfidf = X_test_tfidf.todense()

has_mom = []
word_count = []
count_upper = []
count_exclaim = []
count_AtTheRate = []
count_percent = []
count_LeftBracket = []
count_Quotes = []
count_Star = []
count_BackSlashes = []
count_FrontSlash = []
count_Your = []
count_You = []
count_badword = []
count_percentSpecial = []
count_percentCapital = []
for sentence in X_train:
    has_mom.append(hasYourMom(sentence))
    word_count.append(wordCount(sentence))
    count_upper.append(countUpper(sentence))
    count_exclaim.append(countExclaim(sentence))
    count_AtTheRate.append(countAtTheRate(sentence))
    count_percent.append(countPercent(sentence))
    count_LeftBracket.append(countLeftBracket(sentence))
    count_Quotes.append(countQuotes(sentence))
    count_Star.append(countStar(sentence))
    count_BackSlashes.append(countBackSlashes(sentence))
    count_FrontSlash.append(countFrontSlash(sentence))
    count_Your.append(countYour(sentence))
    count_You.append(countYou(sentence))
    count_badword.append(countBadWords(sentence))
    count_percentSpecial.append(percentSpecial(sentence))
    count_percentCapital.append(percentCapital(sentence))
    
    
has_mom = np.matrix(has_mom)
has_mom = np.transpose(has_mom)
word_count = np.matrix(word_count)
word_count = np.transpose(word_count)    
count_upper = np.matrix(count_upper)
count_upper = np.transpose(count_upper) 
count_exclaim = np.matrix(count_exclaim)
count_exclaim = np.transpose(count_exclaim)
count_AtTheRate = np.matrix(count_AtTheRate)
count_AtTheRate = np.transpose(count_AtTheRate)
count_percent = np.matrix(count_percent)
count_percent = np.transpose(count_percent)
count_LeftBracket = np.matrix(count_LeftBracket)
count_LeftBracket = np.transpose(count_LeftBracket)
count_Quotes = np.matrix(count_Quotes)
count_Quotes = np.transpose(count_Quotes)
count_Star = np.matrix(count_Star)
count_Star = np.transpose(count_Star)
count_BackSlashes = np.matrix(count_BackSlashes)
count_BackSlashes = np.transpose(count_BackSlashes)
count_FrontSlash = np.matrix(count_FrontSlash)
count_FrontSlash = np.transpose(count_FrontSlash)
count_Your = np.matrix(count_Your)
count_Your = np.transpose(count_Your)
count_You = np.matrix(count_You)
count_You = np.transpose(count_You)
count_badword = np.matrix(count_badword)
count_badword = np.transpose(count_badword)
count_percentSpecial = np.matrix(count_percentSpecial)
count_percentSpecial = np.transpose(count_percentSpecial)
count_percentCapital = np.matrix(count_percentCapital)
count_percentCapital = np.transpose(count_percentCapital)

X_train_train = np.zeros((3947, 16))
#count_Your, count_You, count_badword, 
for i in [has_mom, word_count, count_upper, count_exclaim, count_AtTheRate, count_percent, count_LeftBracket,
         count_Quotes, count_Star, count_BackSlashes, count_FrontSlash, count_Your, count_You, count_badword,
          count_percentCapital, count_percentSpecial]:
    X_train_tfidf = np.insert(X_train_tfidf, [X_train_tfidf.shape[1]], i, axis=1)
    
lis = [has_mom, word_count, count_upper, count_exclaim, count_AtTheRate, count_percent, count_LeftBracket,
         count_Quotes, count_Star, count_BackSlashes, count_FrontSlash, count_Your, count_You, count_badword, 
      count_percentCapital, count_percentSpecial]

#print(has_mom.shape) 
print(lis[0][10, 0])
for i in range(16):
    for j in range(3947):
        X_train_train[j, i] = lis[i][j, 0]

X_train_train = sparse.csr_matrix(X_train_train)
X_train_tfidf = sparse.csr_matrix(X_train_tfidf)

has_momT = []
word_countT = []
count_upperT = []
count_exclaimT = []
count_AtTheRateT = []
count_percentT = []
count_LeftBracketT = []
count_QuotesT = []
count_StarT = []
count_BackSlashesT = []
count_FrontSlashT = []
count_YourT = []
count_YouT = []
count_badwordT = []
count_percentSpecialT = []
count_percentCapitalT = []
for sentence in X_test:
    has_momT.append(hasYourMom(sentence))
    word_countT.append(wordCount(sentence))
    count_upperT.append(countUpper(sentence))
    count_exclaimT.append(countExclaim(sentence))
    count_AtTheRateT.append(countAtTheRate(sentence))
    count_percentT.append(countPercent(sentence))
    count_LeftBracketT.append(countLeftBracket(sentence))
    count_QuotesT.append(countQuotes(sentence))
    count_StarT.append(countStar(sentence))
    count_BackSlashesT.append(countBackSlashes(sentence))
    count_FrontSlashT.append(countFrontSlash(sentence))
    count_YourT.append(countYour(sentence))
    count_YouT.append(countYou(sentence))
    count_badwordT.append(countBadWords(sentence))
    count_percentSpecialT.append(percentSpecial(sentence))
    count_percentCapitalT.append(percentCapital(sentence))
    
    
has_momT = np.matrix(has_momT)
has_momT = np.transpose(has_momT)
word_countT = np.matrix(word_countT)
word_countT = np.transpose(word_countT)    
count_upperT = np.matrix(count_upperT)
count_upperT = np.transpose(count_upperT) 
count_exclaimT = np.matrix(count_exclaimT)
count_exclaimT = np.transpose(count_exclaimT)
count_AtTheRateT = np.matrix(count_AtTheRateT)
count_AtTheRateT = np.transpose(count_AtTheRateT)
count_percentT = np.matrix(count_percentT)
count_percentT = np.transpose(count_percentT)
count_LeftBracketT = np.matrix(count_LeftBracketT)
count_LeftBracketT = np.transpose(count_LeftBracketT)
count_QuotesT = np.matrix(count_QuotesT)
count_QuotesT = np.transpose(count_QuotesT)
count_StarT = np.matrix(count_StarT)
count_StarT = np.transpose(count_StarT)
count_BackSlashesT = np.matrix(count_BackSlashesT)
count_BackSlashesT = np.transpose(count_BackSlashesT)
count_FrontSlashT = np.matrix(count_FrontSlashT)
count_FrontSlashT = np.transpose(count_FrontSlashT)
count_YourT = np.matrix(count_YourT)
count_YourT = np.transpose(count_YourT)
count_YouT = np.matrix(count_YouT)
count_YouT = np.transpose(count_YouT)
count_badwordT = np.matrix(count_badwordT)
count_badwordT = np.transpose(count_badwordT)
count_percentSpecialT = np.matrix(count_percentSpecialT)
count_percentSpecialT = np.transpose(count_percentSpecialT)
count_percentCapitalT = np.matrix(count_percentCapitalT)
count_percentCapitalT = np.transpose(count_percentCapitalT)

X_test_test = np.zeros((len(X_test), 16))
lis = [has_momT, word_countT, count_upperT, count_exclaimT, count_AtTheRateT, count_percentT, count_LeftBracketT,
         count_QuotesT, count_StarT, count_BackSlashesT, count_FrontSlashT, count_YourT, count_YouT, count_badwordT,
      count_percentCapitalT, count_percentSpecialT]
for i in [has_momT, word_countT, count_upperT, count_exclaimT, count_AtTheRateT, count_percentT, count_LeftBracketT,
         count_QuotesT, count_StarT, count_BackSlashesT, count_FrontSlashT, count_YourT, count_YouT, count_badwordT,
         count_percentCapitalT, count_percentSpecialT]:
    X_test_tfidf = np.insert(X_test_tfidf, [X_test_tfidf.shape[1]], i, axis=1)

for i in range(16):
    for j in range(len(X_test)):
        X_test_test[j, i] = lis[i][j, 0]
    
X_test_test = sparse.csr_matrix(X_test_test)
X_test_tfidf = sparse.csr_matrix(X_test_tfidf)

0


In [126]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C = 3, class_weight="balanced",warm_start=True)
clf.fit(X_train_train,Y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=3, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
          solver='warn', tol=0.0001, verbose=0, warm_start=True)

In [127]:
predictions = clf.predict_proba(X_test_test)      

In [128]:
# count = 0
# for prediction in range(len(predictions)):
#     if predictions[prediction] == Y_test[prediction]:
#         count += 1
# acc = count/len(predictions)
# aoc = metrics.roc_auc_score(Y_test,predictions)
# data = "**Accuracy** : " + str(acc) + "<br>" + "**AOC Score** : " + str(aoc) 
# display(Markdown(data))
final = []
for prediction in predictions:
    final.append(prediction[1])

fpCount = 0
fp = open("Error Analysis/LogisticRegression_OurFeaturesOnly-FalsePositives.csv","w") 
for index in range(len(final)):
    if (final[index] > 0.5 and Y_test[index] == 0):
        temp_sent = X_test[index].replace(',', '')
        fp.write(str(final[index]) + "," + temp_sent)
        fp.write("\n")
        fpCount += 1
fp.close()

fnCount = 0
fn = open("Error Analysis/LogisticRegression_OurFeaturesOnly-FalseNegatives.csv","w") 
for index in range(len(final)):
    if (final[index] <= 0.5 and Y_test[index] == 1):
        temp_sent = X_test[index].replace(',', '')
        fn.write(str(final[index]) + "," + temp_sent)
        fn.write("\n")
        fnCount += 1
fn.close()
counts = "**False Postives** : " + str(fpCount) + "<br>" + "**False Negatives** : " + str(fnCount)
display(Markdown(counts))
acc = 0
aoc = metrics.roc_auc_score(Y_test,final)
data = "**Accuracy** : " + str(acc) + "<br>" + "**AUC Score** : " + str(aoc) 
display(Markdown(data))              

**False Postives** : 337<br>**False Negatives** : 280

**Accuracy** : 0<br>**AUC Score** : 0.8075631294669166

In [129]:
predictions = clf.predict(X_test_test)  
from sklearn.metrics import precision_recall_fscore_support

from sklearn.metrics import classification_report 

precision, recall, f_score, _ = precision_recall_fscore_support(Y_test, predictions)

print('Precision: ', precision, '  Recall: ', recall, '   F-score: ', f_score)

print(classification_report(Y_test, predictions))

Precision:  [0.85239852 0.55066667]   Recall:  [0.82753327 0.5959596 ]    F-score:  [0.83978187 0.57241857]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84      1954
           1       0.55      0.60      0.57       693

   micro avg       0.77      0.77      0.77      2647
   macro avg       0.70      0.71      0.71      2647
weighted avg       0.77      0.77      0.77      2647



In [130]:
import scipy.stats
temp_test = X_test_test.todense()
print(scipy.stats.pearsonr(temp_test[:, 0], np.transpose(np.matrix(Y_test))))

(array([0.06879611]), array([0.00039708]))


In [131]:
temp_train = X_train_train.todense()
print(scipy.stats.pearsonr(temp_train[:, 0], np.transpose(np.matrix(Y_train))))

(array([0.07897805]), array([6.76476349e-07]))


In [132]:
for i in range(temp_train.shape[1]):
    print(scipy.stats.pearsonr(temp_train[:, i], np.transpose(np.matrix(Y_train))))
    
for i in range(temp_train.shape[1]):
    print(scipy.stats.pearsonr(temp_train[:, i], np.transpose(np.matrix(Y_train))))
    

(array([0.07897805]), array([6.76476349e-07]))
(array([-0.06254075]), array([8.43343984e-05]))
(array([0.06155961]), array([0.00010886]))
(array([0.01769467]), array([0.26639397]))
(array([-0.08058004]), array([3.99713176e-07]))
(array([-0.01717569]), array([0.28067551]))
(array([nan]), array([1.]))
(array([nan]), array([1.]))
(array([0.01355944]), array([0.39441226]))
(array([-0.0318547]), array([0.04537617]))
(array([0.00245153]), array([0.87763403]))
(array([0.16494708]), array([1.78867442e-25]))
(array([0.34027699]), array([1.42335339e-107]))
(array([0.20115177]), array([2.60261058e-37]))
(array([0.06155961]), array([0.00010886]))
(array([-0.01378576]), array([0.38656737]))
(array([0.07897805]), array([6.76476349e-07]))
(array([-0.06254075]), array([8.43343984e-05]))
(array([0.06155961]), array([0.00010886]))
(array([0.01769467]), array([0.26639397]))
(array([-0.08058004]), array([3.99713176e-07]))
(array([-0.01717569]), array([0.28067551]))
(array([nan]), array([1.]))
(array([nan]

/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:3010: RuntimeWarning: invalid value encountered in true_divide
  r = r_num / r_den


In [133]:
for i in range(temp_test.shape[1]):
    print(scipy.stats.pearsonr(temp_test[:, i], np.transpose(np.matrix(Y_test))))
    
for i in range(temp_test.shape[1]):
    print(scipy.stats.pearsonr(temp_test[:, i], np.transpose(np.matrix(Y_test))))

(array([0.06879611]), array([0.00039708]))
(array([-0.08376278]), array([1.59559201e-05]))
(array([0.06354339]), array([0.00107166]))
(array([0.01980222]), array([0.30847687]))
(array([-0.06627731]), array([0.00064478]))
(array([-0.02754746]), array([0.1565155]))
(array([nan]), array([1.]))
(array([nan]), array([1.]))
(array([0.04536217]), array([0.01959901]))
(array([-0.06413898]), array([0.00096091]))
(array([-0.00631924]), array([0.74520526]))
(array([0.19814095]), array([7.69394689e-25]))
(array([0.37921145]), array([2.75852121e-91]))
(array([0.25067009]), array([3.27799189e-39]))
(array([0.06354339]), array([0.00107166]))
(array([0.00101719]), array([0.95828253]))
(array([0.06879611]), array([0.00039708]))
(array([-0.08376278]), array([1.59559201e-05]))
(array([0.06354339]), array([0.00107166]))
(array([0.01980222]), array([0.30847687]))
(array([-0.06627731]), array([0.00064478]))
(array([-0.02754746]), array([0.1565155]))
(array([nan]), array([1.]))
(array([nan]), array([1.]))
(a

In [120]:
a = 'ih ih iwahs af'
len(a.split())

4